version: '3.8'

services:
  db:
    env_file:
      # copy .env_example, modify, and hack away
      - .env
    environment:
      PGPORT: 5433
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready' -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes:
      - upload:/opt/aesheet/upload
    env_file:
      - .env
    environment:
      DEBUG: 1
      DB_HOST: db
      DB_PORT: 5433
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_ENGINE: django.db.backends.postgresql
      DATABASE: postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  upload: