services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    env_file:
      - ./.env.prod.db
  web:
    command: gunicorn sheet.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod.web
    depends_on:
      - db