version: '3.8'

services:
  db:
    environment:
      - POSTGRES_USER=sheetie
      - POSTGRES_PASSWORD=sheetie
      - POSTGRES_DB=sheet_dev
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/aesheet
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
      DB_HOST: db
      SECRET_KEY: foobar
      DB_USERNAME: sheetie
      DB_PASSWORD: sheetie
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: sheet_dev
    depends_on:
      - db
    links:
      - db
volumes:
  postgres_data: