#!/bin/bash
 
NAME="sheet_app"                                  # Name of the application
DJANGODIR=/home/sjl/p/aesheet             # Django project directory
SOCKFILE=/home/sjl/p/aesheet/run/gunicorn.sock  # we will communicate using this unix socket
USER=www-data                                       # the user to run as
GROUP=www-data                                      # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=aesheet.settings             # which settings file should Django use
export ROOT_URL='/ae/sheet/'
export PRODUCTION=1 
PYTHONPATH=/home/sjl/p/:$PYTHONPATH
#export SCRIPT_NAME='/ae/sheet'

echo "Starting $NAME"
 
# Activate the virtual environment
cd $DJANGODIR
source ve/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize
# themselves (do not use --daemon)
exec gunicorn_django \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE
