# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, help_text=b'Freeform notes for the character, intended for quick notes across gaming sessions.'),
        ),
    ]
