# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_auto_20151227_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='edges',
            field=models.ManyToManyField(blank=True, through='sheet.CharacterEdge', to='sheet.EdgeLevel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='characteredge',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.Character'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stat',
            field=models.CharField(choices=[(b'FIT', b'FIT'), (b'REF', b'REF'), (b'LRN', b'LRN'), (b'INT', b'INT'), (b'PSY', b'PSY'), (b'WIL', b'WIL'), (b'CHA', b'CHA'), (b'POS', b'POS'), (b'MOV', b'MOV'), (b'DEX', b'DEX'), (b'IMM', b'IMM')], max_length=64),
        ),
    ]
