# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 20:06
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Skill = apps.get_model('sheet', 'Skill')
    try:
        wc = Skill.objects.get(name="Weapon combat")
    except Skill.DoesNotExist:
        # No weapon combat skill, the migration is useless.
        return

    WeaponTemplate = apps.get_model('sheet', 'WeaponTemplate')
    for tmpl in WeaponTemplate.objects.all():
        if wc in tmpl.base_skill.required_skills.all():
            tmpl.skill2 = tmpl.skill
            tmpl.skill = tmpl.base_skill
            tmpl.base_skill = wc
            tmpl.save()
            print("Updated: {}".format(tmpl.name))


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20160105_0342'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
