# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0009_miscellaneousitem_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetTransientEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransientEffect',
            fields=[
                ('notes', models.TextField(blank=True)),
                ('cc_skill_levels', models.IntegerField(default=0)),
                ('fit', models.IntegerField(default=0)),
                ('ref', models.IntegerField(default=0)),
                ('lrn', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('psy', models.IntegerField(default=0)),
                ('wil', models.IntegerField(default=0)),
                ('cha', models.IntegerField(default=0)),
                ('pos', models.IntegerField(default=0)),
                ('mov', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('imm', models.IntegerField(default=0)),
                ('saves_vs_fire', models.IntegerField(default=0)),
                ('saves_vs_cold', models.IntegerField(default=0)),
                ('saves_vs_lightning', models.IntegerField(default=0)),
                ('saves_vs_poison', models.IntegerField(default=0)),
                ('saves_vs_all', models.IntegerField(default=0)),
                ('run_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('swim_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('climb_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fly_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[(b'enhancement', b'enhancement'), (b'luck', b'luck'), (b'circumstance', b'circumstance')], default=b'enhancement', help_text=b'Effect type.  With the exception of circumstance bonus, only highest effect of a single type will take effect.', max_length=256)),
                ('tech_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.TechLevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sheettransienteffect',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.TransientEffect'),
        ),
        migrations.AddField(
            model_name='sheettransienteffect',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.Sheet'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='transient_effects',
            field=models.ManyToManyField(blank=True, through='sheet.SheetTransientEffect', to='sheet.TransientEffect'),
        ),
    ]
