# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_spells_to_transient_effects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='spell_effects',
        ),
        migrations.DeleteModel(
            name='SpellEffect',
        ),
    ]
