# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0012_auto_20160209_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armortemplate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='ammo_weight',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weapontemplate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
