# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0018_remove_character_edges_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='extra_weight_carried',
        ),
    ]
