# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0019_remove_sheet_extra_weight_carried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgelevel',
            name='skill_bonuses',
        ),
        migrations.AlterField(
            model_name='edgeskillbonus',
            name='edge_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_skill_bonuses', to='sheet.EdgeLevel'),
        ),
    ]
