# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0024_auto_20161215_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefirearm',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Weapon's inherent accurace modifier.  Larger is better.", max_digits=4),
        ),
        migrations.AddField(
            model_name='basefirearm',
            name='barrel_length',
            field=models.IntegerField(default=100, help_text="Weapon's barrel length in millimeters"),
        ),
        migrations.AddField(
            model_name='basefirearm',
            name='sight',
            field=models.IntegerField(default=100, help_text="Weapon's sight modifier in millimeters"),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='bullet_type',
            field=models.CharField(help_text='Make of the ammo, such as full metal jacket.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='label',
            field=models.CharField(help_text='Ammunition caliber, which should also distinguish between barrel lengths and such.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='type',
            field=models.CharField(default='P', help_text='Damage type of the ammo.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='velocity',
            field=models.IntegerField(help_text='Velocity of the bullet at muzzle in meters per second.  Used to calculate recoil.'),
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='Weight of a single round in grams.  Used to calculate recoil.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='armorspecialquality',
            name='hear',
            field=models.IntegerField(default=0, help_text='Modifier for the general hearing INT check'),
        ),
        migrations.AlterField(
            model_name='armorspecialquality',
            name='smell',
            field=models.IntegerField(default=0, help_text='Modifier for the general smell & taste INT check'),
        ),
        migrations.AlterField(
            model_name='armorspecialquality',
            name='surprise',
            field=models.IntegerField(default=0, help_text='Modifier for the surprise check'),
        ),
        migrations.AlterField(
            model_name='armorspecialquality',
            name='type',
            field=models.CharField(choices=[('enhancement', 'enhancement'), ('luck', 'luck'), ('circumstance', 'circumstance')], default='enhancement', help_text='Effect type.  With the exception of circumstance bonus, only highest effect of a single type will take effect.', max_length=256),
        ),
        migrations.AlterField(
            model_name='armorspecialquality',
            name='vision',
            field=models.IntegerField(default=0, help_text='Modifier for the general vision INT check'),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='autofire_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='duration',
            field=models.DecimalField(decimal_places=3, default=0.1, help_text='Modifier for recoil.  In principle, time in seconds from the muzzle break, whatever that means.  Bigger is better.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='short_name',
            field=models.CharField(blank=True, help_text='This is used when the name must be fit to a small space', max_length=64),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weapon stock modifier for recoil calculation.  Larger is better.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='weapon_class_modifier',
            field=models.DecimalField(decimal_places=2, default=6, help_text='ROF modifier for weapon class.  Generally from 6-15, smaller is better.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, help_text='Freeform notes for the character, intended for quick notes across gaming sessions.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portraits'),
        ),
        migrations.AlterField(
            model_name='character',
            name='private',
            field=models.BooleanField(default=False, help_text='If set, access to the character will be denied for other users. The character will also be hidden in lists.  As a rule of thumb, only the GM should mark characters as private.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='size',
            field=models.CharField(choices=[('F', 'Fine'), ('D', 'Diminutive'), ('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan'), ('C', 'Colossal')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='characterlogentry',
            name='entry',
            field=models.TextField(blank=True, help_text='Additional information about this entry, input by the user.'),
        ),
        migrations.AlterField(
            model_name='characterlogentry',
            name='entry_type',
            field=models.PositiveIntegerField(choices=[(0, 'stat'), (1, 'skill'), (2, 'edge'), (3, 'non-field')], default=0),
        ),
        migrations.AlterField(
            model_name='characterlogentry',
            name='removed',
            field=models.BooleanField(default=False, help_text='Setting this means that the edge or skill was removed instead of added.'),
        ),
        migrations.AlterField(
            model_name='edgelevel',
            name='hear',
            field=models.IntegerField(default=0, help_text='Modifier for the general hearing INT check'),
        ),
        migrations.AlterField(
            model_name='edgelevel',
            name='smell',
            field=models.IntegerField(default=0, help_text='Modifier for the general smell & taste INT check'),
        ),
        migrations.AlterField(
            model_name='edgelevel',
            name='surprise',
            field=models.IntegerField(default=0, help_text='Modifier for the surprise check'),
        ),
        migrations.AlterField(
            model_name='edgelevel',
            name='vision',
            field=models.IntegerField(default=0, help_text='Modifier for the general vision INT check'),
        ),
        migrations.AlterField(
            model_name='firearmammunitiontype',
            name='short_label',
            field=models.CharField(help_text='Matches the respective field in ammunition', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='location',
            field=models.CharField(blank=True, help_text='Indicate where the item(s) is stored', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='order',
            field=models.IntegerField(default=0, help_text='explicit ordering for the entries'),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='unit_weight',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Item weight in kilograms', max_digits=6),
        ),
        migrations.AlterField(
            model_name='rangedweapon',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'double'), (3, 'triple'), (4, 'quadruple')], default=1),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='short_name',
            field=models.CharField(blank=True, help_text='This is used when the name must be fit to a small space', max_length=64),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='type',
            field=models.CharField(default='P', max_length=5),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='weapon_type',
            field=models.CharField(choices=[('thrown', 'thrown'), ('xbow', 'xbow'), ('bow', 'bow')], default='thrown', max_length=10),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='size',
            field=models.CharField(choices=[('F', 'Fine'), ('D', 'Diminutive'), ('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan'), ('C', 'Colossal')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stat',
            field=models.CharField(choices=[('FIT', 'FIT'), ('REF', 'REF'), ('LRN', 'LRN'), ('INT', 'INT'), ('PSY', 'PSY'), ('WIL', 'WIL'), ('CHA', 'CHA'), ('POS', 'POS'), ('MOV', 'MOV'), ('DEX', 'DEX'), ('IMM', 'IMM')], max_length=64),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Combat', 'Combat'), ('Specialty', 'Specialty'), ('Education', 'Education'), ('Social', 'Social'), ('Mystical', 'Mystical'), ('Mage', 'Mage'), ('Priest', 'Priest'), ('Language', 'Language')], max_length=64),
        ),
        migrations.AlterField(
            model_name='transienteffect',
            name='hear',
            field=models.IntegerField(default=0, help_text='Modifier for the general hearing INT check'),
        ),
        migrations.AlterField(
            model_name='transienteffect',
            name='smell',
            field=models.IntegerField(default=0, help_text='Modifier for the general smell & taste INT check'),
        ),
        migrations.AlterField(
            model_name='transienteffect',
            name='surprise',
            field=models.IntegerField(default=0, help_text='Modifier for the surprise check'),
        ),
        migrations.AlterField(
            model_name='transienteffect',
            name='type',
            field=models.CharField(choices=[('enhancement', 'enhancement'), ('luck', 'luck'), ('circumstance', 'circumstance')], default='enhancement', help_text='Effect type.  With the exception of circumstance bonus, only highest effect of a single type will take effect.', max_length=256),
        ),
        migrations.AlterField(
            model_name='transienteffect',
            name='vision',
            field=models.IntegerField(default=0, help_text='Modifier for the general vision INT check'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'double'), (3, 'triple'), (4, 'quadruple')], default=1),
        ),
        migrations.AlterField(
            model_name='weaponquality',
            name='max_fit',
            field=models.IntegerField(default=90, help_text='Applies for bows, this is the maximum FIT the weapon pull adjusts to.  This caps the damage and range of the weapon in case the character has a higher FIT than this.'),
        ),
        migrations.AlterField(
            model_name='weaponspecialquality',
            name='hear',
            field=models.IntegerField(default=0, help_text='Modifier for the general hearing INT check'),
        ),
        migrations.AlterField(
            model_name='weaponspecialquality',
            name='smell',
            field=models.IntegerField(default=0, help_text='Modifier for the general smell & taste INT check'),
        ),
        migrations.AlterField(
            model_name='weaponspecialquality',
            name='surprise',
            field=models.IntegerField(default=0, help_text='Modifier for the surprise check'),
        ),
        migrations.AlterField(
            model_name='weaponspecialquality',
            name='type',
            field=models.CharField(choices=[('enhancement', 'enhancement'), ('luck', 'luck'), ('circumstance', 'circumstance')], default='enhancement', help_text='Effect type.  With the exception of circumstance bonus, only highest effect of a single type will take effect.', max_length=256),
        ),
        migrations.AlterField(
            model_name='weaponspecialquality',
            name='vision',
            field=models.IntegerField(default=0, help_text='Modifier for the general vision INT check'),
        ),
        migrations.AlterField(
            model_name='weapontemplate',
            name='short_name',
            field=models.CharField(blank=True, help_text='This is used when the name must be fit to a small space', max_length=64),
        ),
        migrations.AlterField(
            model_name='weapontemplate',
            name='type',
            field=models.CharField(default='S', max_length=5),
        ),
        migrations.AlterField(
            model_name='wound',
            name='damage',
            field=models.PositiveIntegerField(default=0, help_text='Initial damage from the wound.'),
        ),
        migrations.AlterField(
            model_name='wound',
            name='damage_type',
            field=models.CharField(choices=[('S', 'Slash'), ('P', 'Pierce'), ('B', 'Bludgeon'), ('R', 'Burn')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='wound',
            name='effect',
            field=models.CharField(blank=True, help_text='Initial effect from the injury.', max_length=64),
        ),
        migrations.AlterField(
            model_name='wound',
            name='healed',
            field=models.PositiveIntegerField(default=0, help_text='Healed damage.  When this becomes equal to damage, the wound is healed.'),
        ),
        migrations.AlterField(
            model_name='wound',
            name='location',
            field=models.CharField(choices=[('H', 'Head'), ('T', 'Torso'), ('RA', 'Right arm'), ('LA', 'Left arm'), ('RL', 'Right leg'), ('LL', 'Left leg')], default='T', max_length=2),
        ),
    ]
