# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0026_auto_20161227_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirearmAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('target_i_mod', models.IntegerField(default=0)),
                ('to_hit_mod', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Weapon's inherent accuracy modifier. Larger is better.", max_digits=4),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='duration',
            field=models.DecimalField(decimal_places=3, default=0.1, help_text='Modifier for recoil.  In principle, time in seconds from the muzzle break, whatever that means. Bigger is better.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weapon stock modifier for recoil calculation. Larger is better.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='weapon_class_modifier',
            field=models.DecimalField(decimal_places=2, default=6, help_text='ROF modifier for weapon class. Generally from 6-15, smaller is better.', max_digits=4),
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('firearmaddon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sheet.FirearmAddOn')),
                ('sight', models.IntegerField(default=1000, help_text="Overrides weapon's sight modifier")),
            ],
            options={
                'abstract': False,
            },
            bases=('sheet.firearmaddon',),
        ),
        migrations.AddField(
            model_name='firearmaddon',
            name='tech_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.TechLevel'),
        ),
        migrations.AddField(
            model_name='firearm',
            name='add_ons',
            field=models.ManyToManyField(blank=True, to='sheet.FirearmAddOn'),
        ),
        migrations.AddField(
            model_name='firearm',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firearms_using_scope', to='sheet.Scope'),
        ),
    ]
