# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0027_auto_20161227_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefirearm',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='weapontemplate',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=7),
        ),
    ]
