# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0028_auto_20190801_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearmaddon',
            name='perks',
            field=models.ManyToManyField(blank=True, to='sheet.EdgeLevel'),
        ),
    ]
