# Generated by Django 2.2 on 2023-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0034_characteredge_ignore_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wound',
            name='damage_type',
            field=models.CharField(choices=[('S', 'Slash'), ('P', 'Pierce'), ('B', 'Bludgeon'), ('R', 'Burn')], default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='wound',
            name='location',
            field=models.CharField(choices=[('H', 'Head'), ('T', 'Torso'), ('RA', 'Right arm'), ('LA', 'Left arm'), ('RL', 'Right leg'), ('LL', 'Left leg')], default='T', max_length=10),
        ),
    ]
