# Generated by Django 4.2.2 on 2023-07-05 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0036_alter_ammunition_id_alter_armor_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calibre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ammunition calibre, which should also distinguish between barrel lengths and such.",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ammunition",
            name="velocity",
            field=models.IntegerField(
                help_text="Velocity of the bullet at muzzle in meters per second. Used to calculate recoil."
            ),
        ),
        migrations.AlterField(
            model_name="ammunition",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Weight of a single round in grams. Used to calculate recoil.",
                max_digits=7,
            ),
        ),
        migrations.AddField(
            model_name="ammunition",
            name="calibre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.calibre",
            ),
        ),
        migrations.AddField(
            model_name="firearmammunitiontype",
            name="calibre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.calibre",
            ),
        ),
    ]
