# Generated by Django 4.2.2 on 2023-07-05 00:33

from django.db import migrations


def forwards(apps, schema_editor):
    FirearmAmmunitionType = apps.get_model('sheet', 'FirearmAmmunitionType')
    Ammunition = apps.get_model('sheet', 'Ammunition')
    Calibre = apps.get_model('sheet', 'Calibre')

    for ammo_type in FirearmAmmunitionType.objects.all():
        cal = Calibre.objects.get_or_create(name=ammo_type.short_label)
        ammo_type.calibre = cal[0]
        ammo_type.save()

    for ammo in Ammunition.objects.all():
        cal = Calibre.objects.get_or_create(name=ammo.label)
        ammo.calibre = cal[0]
        ammo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0037_calibre_alter_ammunition_velocity_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
