# Generated by Django 4.2.2 on 2023-07-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0038_populate_calibre_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="basefirearm",
            name="ammo_types",
            field=models.ManyToManyField(
                through="sheet.FirearmAmmunitionType", to="sheet.calibre"
            ),
        ),
    ]
