# Generated by Django 4.2.2 on 2023-07-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0039_basefirearm_ammo_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basefirearm",
            old_name="ammo_types",
            new_name="ammunition_types",
        ),
        migrations.AlterField(
            model_name="firearmammunitiontype",
            name="firearm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sheet.basefirearm"
            ),
        ),
    ]
