# Generated by Django 4.2.2 on 2023-07-05 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0040_rename_ammo_types_basefirearm_ammunition_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ammunition",
            name="label",
        ),
        migrations.RemoveField(
            model_name="firearmammunitiontype",
            name="short_label",
        ),
    ]
