# Generated by Django 4.2.2 on 2023-07-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0041_remove_ammunition_label_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ammunition",
            options={"ordering": ["calibre__name", "bullet_type"]},
        ),
        migrations.AlterField(
            model_name="ammunition",
            name="calibre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sheet.calibre"
            ),
        ),
        migrations.AlterField(
            model_name="firearmammunitiontype",
            name="calibre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sheet.calibre"
            ),
        ),
    ]
