# Generated by Django 4.2.2 on 2023-07-06 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0042_alter_ammunition_options_alter_ammunition_calibre_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calibre",
            options={"ordering": ["name"]},
        ),
    ]
