# Generated by Django 4.2.2 on 2023-07-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0043_alter_calibre_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="armortemplate",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="armortemplate",
            name="name",
            field=models.CharField(
                max_length=256, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
