# Generated by Django 4.2.2 on 2023-07-06 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0044_alter_armortemplate_options_alter_armortemplate_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techlevel",
            options={"ordering": ["name"]},
        ),
    ]
