# Generated by Django 4.2.2 on 2023-07-06 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0045_alter_techlevel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="armorquality",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="weaponquality",
            options={"ordering": ["name"]},
        ),
    ]
