# Generated by Django 4.2.2 on 2023-07-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0046_alter_armorquality_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="armorspecialquality",
            name="tech_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.techlevel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weaponspecialquality",
            name="tech_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.techlevel",
            ),
            preserve_default=False,
        ),
    ]
