# Generated by Django 4.2.2 on 2023-07-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0047_armorspecialquality_tech_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basefirearm",
            name="magazine_size",
            field=models.IntegerField(
                default=8, help_text="Typical clip size for the firearm"
            ),
        ),
    ]
