# Generated by Django 4.2.2 on 2023-07-11 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0048_basefirearm_magazine_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetFirearm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ons",
                    models.ManyToManyField(blank=True, to="sheet.firearmaddon"),
                ),
                (
                    "ammo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet.ammunition",
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet.basefirearm",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sheet.scope",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sheet.sheet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sheet",
            name="firearms_v2",
            field=models.ManyToManyField(
                blank=True, through="sheet.SheetFirearm", to="sheet.basefirearm"
            ),
        ),
    ]
