# Generated by Django 4.2.2 on 2023-07-11 23:51

from django.db import migrations


def forwards(apps, schema_editor):
    Sheet = apps.get_model('sheet', 'Sheet')
    SheetFirearm = apps.get_model('sheet', 'SheetFirearm')

    for sheet in Sheet.objects.all():
        for fa in sheet.firearms.all():
            sfa = SheetFirearm.objects.create(
                sheet=sheet,
                base=fa.base,
                ammo=fa.ammo,
                scope=fa.scope,
            )
            for add_on in fa.add_ons.all():
                sfa.add_ons.add(add_on)


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0049_sheetfirearm_sheet_firearms_v2"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
