# Generated by Django 4.2.2 on 2023-07-12 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0051_remove_sheet_firearms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sheet",
            old_name="firearms_v2",
            new_name="firearms",
        ),
    ]
