# Generated by Django 4.2.2 on 2023-07-12 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0052_rename_firearms_v2_sheet_firearms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Firearm",
        ),
    ]
