# Generated by Django 4.2.2 on 2023-07-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0053_delete_firearm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheetfirearm",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firearms_using_scope",
                to="sheet.scope",
            ),
        ),
        migrations.CreateModel(
            name="SheetFirearmMagazine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField()),
                ("current", models.PositiveSmallIntegerField()),
                (
                    "sheet_firearm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magazines",
                        to="sheet.sheetfirearm",
                    ),
                ),
            ],
        ),
    ]
