# Generated by Django 4.2.2 on 2023-07-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0054_alter_sheetfirearm_scope_sheetfirearmmagazine"),
    ]

    operations = [
        migrations.AddField(
            model_name="basefirearm",
            name="magazine_weight",
            field=models.DecimalField(
                decimal_places=4,
                default=0.35,
                help_text="Empty magazine weight",
                max_digits=7,
            ),
        ),
    ]
