# Generated by Django 4.2.2 on 2023-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0055_basefirearm_magazine_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetfirearm",
            name="use_type",
            field=models.CharField(
                choices=[("FULL", "Full"), ("PRI", "Primary"), ("SEC", "Secondary")],
                default="FULL",
                max_length=10,
            ),
        ),
    ]
