# Generated by Django 5.0.6 on 2024-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0056_sheetfirearm_use_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="edgelevel",
            name="armor_dr",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Overall damage reduction",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="edgelevel",
            name="armor_l",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Overall lethality reduction",
                max_digits=4,
            ),
        ),
    ]
