# Generated by Django 5.0.6 on 2024-07-01 20:34

from django.db import migrations


def forwards(apps, schema_editor):
    Wound = apps.get_model('sheet', 'Wound')

    for wound in Wound.objects.all():
        sheet = wound.character.sheet_set.first()
        if not sheet:
            sheet = wound.character.sheet_set.create(owner=wound.character.owner)
        wound.sheet = sheet
        wound.save()

    Character = apps.get_model('sheet', 'Character')

    for char in Character.objects.all():
        if char.stamina_damage:
            sheet = char.sheet_set.first()
            if not sheet:
                sheet = wound.character.sheet_set.create(owner=wound.character.owner)
            sheet.stamina_damage = char.stamina_damage


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0058_sheet_stamina_damage_wound_sheet"),
    ]
    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
