# Generated by Django 5.0.6 on 2024-07-02 19:39

import django.db.models.deletion
import sheet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0060_characterlogentry_sheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sheet.campaign"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheetsets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(sheet.models.PrivateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SheetSetSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sheet.sheet"
                    ),
                ),
                (
                    "sheet_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sheet.sheetset"
                    ),
                ),
            ],
            bases=(sheet.models.PrivateMixin, models.Model),
        ),
        migrations.AddField(
            model_name="sheetset",
            name="sheets",
            field=models.ManyToManyField(
                through="sheet.SheetSetSheet", to="sheet.sheet"
            ),
        ),
    ]
