# Generated by Django 5.0.6 on 2024-07-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0061_sheetset_sheetsetsheet_sheetset_sheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetsetsheet",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sheetset",
            name="sheets",
            field=models.ManyToManyField(
                blank=True, through="sheet.SheetSetSheet", to="sheet.sheet"
            ),
        ),
    ]
