# Generated by Django 5.0.6 on 2024-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0062_sheetsetsheet_order_alter_sheetset_sheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="edgelevel",
            name="pain_resistance",
            field=models.IntegerField(default=0),
        ),
    ]
