# Generated by Django 5.0.6 on 2024-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0063_edgelevel_pain_resistance"),
    ]

    operations = [
        migrations.AddField(
            model_name="armortemplate",
            name="is_powered",
            field=models.BooleanField(
                default=False,
                help_text="Powered armor, allowing skill to affect REF and FIT modifiers",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="powered_fit_mod",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skill",
            name="powered_ref_counter",
            field=models.IntegerField(default=0),
        ),
    ]
