# Generated by Django 5.0.6 on 2024-07-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0064_armortemplate_is_powered_skill_powered_fit_mod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="powered_fit_mod",
            field=models.IntegerField(
                default=0,
                help_text="Grant this many points of FIT bonus using a powered armor",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="powered_ref_counter",
            field=models.IntegerField(
                default=0,
                help_text="Counters this many points of REF penalty using a powered armor",
            ),
        ),
    ]
