# Generated by Django 5.0.6 on 2024-07-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0066_remove_basefirearm_range_e_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefirearm",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="This is used when the name must fit to a small space",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="rangedweapontemplate",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="This is used when the name must fit to a small space",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="weapontemplate",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="This is used when the name must fit to a small space",
                max_length=64,
            ),
        ),
    ]
