# Generated by Django 5.0.6 on 2024-07-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0067_alter_basefirearm_short_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edge2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="edgelevel",
            name="edge2",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sheet.edge2"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="required_edges2",
            field=models.ManyToManyField(blank=True, to="sheet.edge2"),
        ),
    ]
