# Generated by Django 5.0.6 on 2024-07-14 14:56

from django.db import migrations


def edges(apps, schema_editor):
    Edge = apps.get_model('sheet', 'Edge')
    Edge2 = apps.get_model('sheet', 'Edge2')

    for edge in Edge.objects.all():
        e2 = Edge2.objects.get_or_create(name=edge.name)
        e2.description = edge.description
        e2.notes = edge.notes
        e2.save()


def edge_levels(apps, schema_editor):
    EdgeLevel = apps.get_model('sheet', 'EdgeLevel')
    Edge2 = apps.get_model('sheet', 'Edge2')

    for edge_level in EdgeLevel.objects.all():
        edge_level.edge2 = Edge2.objects.get(name=edge_level.edge.name)
        edge_level.save()


def skills(apps, schema_editor):
    Skill = apps.get_model('sheet', 'Skill')
    Edge2 = apps.get_model('sheet', 'Edge2')

    for skill in Skill.objects.all():
        for e in skill.required_edges:
            skill.required_edges2.add(Edge2.objects.get(name=e.name))


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0068_edge2_edgelevel_edge2_skill_required_edges2"),
    ]

    operations = [
        migrations.RunPython(edges, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(edge_levels, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(skills, reverse_code=migrations.RunPython.noop)
    ]
