# Generated by Django 5.0.6 on 2024-07-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0069_edge_to_edge2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edgelevel",
            name="edge2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sheet.edge2"
            ),
        ),
    ]
