# Generated by Django 5.0.6 on 2024-07-14 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0070_alter_edgelevel_edge2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edgelevel",
            options={"ordering": ("level",)},
        ),
        migrations.RemoveField(
            model_name="edgelevel",
            name="edge",
        ),
    ]
