# Generated by Django 5.0.6 on 2024-07-14 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0071_alter_edgelevel_options_remove_edgelevel_edge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edgelevel",
            old_name="edge2",
            new_name="edge",
        ),
    ]
