# Generated by Django 5.0.6 on 2024-07-14 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0072_rename_edge2_edgelevel_edge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="required_edges",
        ),
    ]
