# Generated by Django 5.0.6 on 2024-07-14 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0074_rename_required_edges2_skill_required_edges"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Edge",
        ),
    ]
