# Generated by Django 5.0.6 on 2024-07-16 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0076_rename_edge2_edge"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseFirearmNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="This is used when the name must fit to a small space",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("notes", models.CharField(blank=True, max_length=64)),
                (
                    "draw_initiative",
                    models.IntegerField(blank=True, default=-3, null=True),
                ),
                ("durability", models.IntegerField(default=5)),
                ("dp", models.IntegerField(default=10)),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=7),
                ),
                ("autofire_rpm", models.IntegerField(blank=True, null=True)),
                (
                    "autofire_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                ("sweep_fire_disabled", models.BooleanField(default=False)),
                ("restricted_burst_rounds", models.IntegerField(default=0)),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Weapon stock modifier for recoil calculation. Larger is better.",
                        max_digits=4,
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.1,
                        help_text="Modifier for recoil.  In principle, time in seconds from the muzzle break, whatever that means. Bigger is better.",
                        max_digits=5,
                    ),
                ),
                (
                    "weapon_class_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=6,
                        help_text="ROF modifier for weapon class. Generally from 6-15, smaller is better.",
                        max_digits=4,
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Weapon's inherent accuracy modifier. Larger is better.",
                        max_digits=4,
                    ),
                ),
                (
                    "sight",
                    models.IntegerField(
                        default=100, help_text="Weapon's sight modifier in millimeters"
                    ),
                ),
                (
                    "barrel_length",
                    models.IntegerField(
                        default=100, help_text="Weapon's barrel length in millimeters"
                    ),
                ),
                ("target_initiative", models.IntegerField(default=-2)),
                (
                    "magazine_size",
                    models.IntegerField(
                        default=8, help_text="Typical clip size for the firearm"
                    ),
                ),
                (
                    "magazine_weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.35,
                        help_text="Empty magazine weight",
                        max_digits=7,
                    ),
                ),
                (
                    "ammunition_types",
                    models.ManyToManyField(
                        through="sheet.FirearmAmmunitionType", to="sheet.calibre"
                    ),
                ),
                (
                    "tech_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet.techlevel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="firearmammunitiontype",
            name="firearm_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.basefirearmnew",
            ),
        ),
        migrations.AddField(
            model_name="sheet",
            name="firearms_new",
            field=models.ManyToManyField(
                blank=True, through="sheet.SheetFirearm", to="sheet.basefirearmnew"
            ),
        ),
        migrations.AddField(
            model_name="sheetfirearm",
            name="base_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.basefirearmnew",
            ),
        ),
        migrations.CreateModel(
            name="RangedWeaponTemplateNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="This is used when the name must fit to a small space",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("notes", models.CharField(blank=True, max_length=64)),
                (
                    "draw_initiative",
                    models.IntegerField(blank=True, default=-3, null=True),
                ),
                ("durability", models.IntegerField(default=5)),
                ("dp", models.IntegerField(default=10)),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=7),
                ),
                ("num_dice", models.IntegerField(default=1)),
                ("dice", models.IntegerField(default=6)),
                ("extra_damage", models.IntegerField(default=0)),
                ("leth", models.IntegerField(default=5)),
                ("plus_leth", models.IntegerField(default=0)),
                (
                    "roa",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
                ),
                ("bypass", models.IntegerField(default=0)),
                ("type", models.CharField(default="P", max_length=5)),
                (
                    "ammo_weight",
                    models.DecimalField(decimal_places=3, default=0.1, max_digits=6),
                ),
                ("target_initiative", models.IntegerField(default=-2)),
                ("range_s", models.IntegerField()),
                ("range_m", models.IntegerField()),
                ("range_l", models.IntegerField()),
                (
                    "tech_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet.techlevel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="rangedweapon",
            name="base_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.rangedweapontemplatenew",
            ),
        ),
        migrations.CreateModel(
            name="SkillNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("can_be_defaulted", models.BooleanField(default=True)),
                ("is_specialization", models.BooleanField(default=False)),
                ("skill_cost_0", models.IntegerField(blank=True, null=True)),
                ("skill_cost_1", models.IntegerField(blank=True, null=True)),
                ("skill_cost_2", models.IntegerField(blank=True, null=True)),
                ("skill_cost_3", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(choices=[], max_length=64)),
                ("stat", models.CharField(choices=[], max_length=64)),
                (
                    "powered_ref_counter",
                    models.IntegerField(
                        default=0,
                        help_text="Counters this many points of REF penalty using a powered armor",
                    ),
                ),
                (
                    "powered_fit_mod",
                    models.IntegerField(
                        default=0,
                        help_text="Grant this many points of FIT bonus using a powered armor",
                    ),
                ),
                ("required_edges", models.ManyToManyField(blank=True, to="sheet.edge")),
                (
                    "required_skills",
                    models.ManyToManyField(blank=True, to="sheet.skillnew"),
                ),
                (
                    "tech_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet.techlevel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="rangedweapontemplatenew",
            name="base_skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_skill_for_%(class)s",
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="rangedweapontemplatenew",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_%(class)s",
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="rangedweapontemplatenew",
            name="skill2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_for_%(class)s",
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="basefirearmnew",
            name="base_skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_skill_for_%(class)s",
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="basefirearmnew",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_%(class)s",
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="basefirearmnew",
            name="skill2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_for_%(class)s",
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="characterlogentry",
            name="skill_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="characterskill",
            name="skill_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.skillnew",
            ),
        ),
        migrations.AddField(
            model_name="edgeskillbonus",
            name="skill_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.skillnew",
            ),
        ),
        migrations.CreateModel(
            name="WeaponTemplateNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="This is used when the name must fit to a small space",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("notes", models.CharField(blank=True, max_length=64)),
                (
                    "draw_initiative",
                    models.IntegerField(blank=True, default=-3, null=True),
                ),
                ("durability", models.IntegerField(default=5)),
                ("dp", models.IntegerField(default=10)),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=7),
                ),
                ("num_dice", models.IntegerField(default=1)),
                ("dice", models.IntegerField(default=6)),
                ("extra_damage", models.IntegerField(default=0)),
                ("leth", models.IntegerField(default=5)),
                ("plus_leth", models.IntegerField(default=0)),
                (
                    "roa",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
                ),
                ("bypass", models.IntegerField(default=0)),
                ("type", models.CharField(default="S", max_length=5)),
                ("ccv", models.IntegerField(default=10)),
                ("ccv_unskilled_modifier", models.IntegerField(default=-10)),
                ("defense_leth", models.IntegerField(default=5)),
                ("is_lance", models.BooleanField(default=False)),
                ("is_shield", models.BooleanField(default=False)),
                (
                    "base_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_skill_for_%(class)s",
                        to="sheet.skillnew",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_%(class)s",
                        to="sheet.skillnew",
                    ),
                ),
                (
                    "skill2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_for_%(class)s",
                        to="sheet.skillnew",
                    ),
                ),
                (
                    "tech_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet.techlevel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="base_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.weapontemplatenew",
            ),
        ),
    ]
