# Generated by Django 5.0.6 on 2024-07-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0076_rename_edge2_edge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("can_be_defaulted", models.BooleanField(default=True)),
                ("is_specialization", models.BooleanField(default=False)),
                ("skill_cost_0", models.IntegerField(blank=True, null=True)),
                ("skill_cost_1", models.IntegerField(blank=True, null=True)),
                ("skill_cost_2", models.IntegerField(blank=True, null=True)),
                ("skill_cost_3", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(choices=[], max_length=64)),
                ("stat", models.CharField(choices=[], max_length=64)),
                (
                    "powered_ref_counter",
                    models.IntegerField(
                        default=0,
                        help_text="Counters this many points of REF penalty using a powered armor",
                    ),
                ),
                (
                    "powered_fit_mod",
                    models.IntegerField(
                        default=0,
                        help_text="Grant this many points of FIT bonus using a powered armor",
                    ),
                ),
                ("required_edges", models.ManyToManyField(blank=True, to="sheet.edge")),
                (
                    "required_skills",
                    models.ManyToManyField(blank=True, to="sheet.skill2"),
                ),
                (
                    "tech_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet.techlevel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
