# Generated by Django 5.0.6 on 2024-07-16 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0079_remove_basefirearm_ammunition_types_and_more_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firearmammunitiontype",
            old_name="firearm_new",
            new_name="firearm",
        ),
        migrations.RenameField(
            model_name="sheet",
            old_name="firearms_new",
            new_name="firearms",
        ),
        migrations.RenameField(
            model_name="sheetfirearm",
            old_name="base_new",
            new_name="base",
        ),
    ]
