# Generated by Django 5.0.6 on 2024-07-16 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0080_rename_firearm_new_firearmammunitiontype_firearm_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaseFirearm",
        ),
    ]
