# Generated by Django 5.0.6 on 2024-07-16 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0081_delete_basefirearm"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BaseFirearmNew",
            new_name="BaseFirearm",
        ),
    ]
