# Generated by Django 5.0.6 on 2024-07-16 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0083_alter_characterskill_skill_new"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterskill",
            options={"ordering": ("skill_new__name",)},
        ),
        migrations.AlterUniqueTogether(
            name="characterskill",
            unique_together={("character", "skill_new")},
        ),
        migrations.RemoveField(
            model_name="characterskill",
            name="skill",
        ),
    ]
