# Generated by Django 5.0.6 on 2024-07-16 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0085_alter_characterskill_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterlogentry",
            name="skill",
        ),
    ]
