# Generated by Django 5.0.6 on 2024-07-16 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0086_remove_characterlogentry_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterlogentry",
            old_name="skill_new",
            new_name="skill",
        ),
    ]
