# Generated by Django 5.0.6 on 2024-07-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0087_rename_skill_new_characterlogentry_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edgeskillbonus",
            name="skill_new",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sheet.skillnew"
            ),
        ),
    ]
