# Generated by Django 5.0.6 on 2024-07-16 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0088_alter_edgeskillbonus_skill_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edgeskillbonus",
            name="skill",
        ),
    ]
