# Generated by Django 5.0.6 on 2024-07-16 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0089_remove_edgeskillbonus_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edgeskillbonus",
            old_name="skill_new",
            new_name="skill",
        ),
    ]
