# Generated by Django 5.0.6 on 2024-07-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0090_rename_skill_new_edgeskillbonus_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weapon",
            name="base_new",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.weapontemplatenew",
            ),
        ),
    ]
