# Generated by Django 5.0.6 on 2024-07-16 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0091_alter_weapon_base_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weapon",
            name="base",
        ),
    ]
