# Generated by Django 5.0.6 on 2024-07-16 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0092_remove_weapon_base"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weapon",
            old_name="base_new",
            new_name="base",
        ),
    ]
