# Generated by Django 5.0.6 on 2024-07-16 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0093_rename_base_new_weapon_base"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeaponTemplate",
        ),
    ]
