# Generated by Django 5.0.6 on 2024-07-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0094_delete_weapontemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rangedweapon",
            name="base_new",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet.rangedweapontemplatenew",
            ),
        ),
    ]
