# Generated by Django 5.0.6 on 2024-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0095_alter_rangedweapon_base_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rangedweapon",
            name="base",
        ),
    ]
