# Generated by Django 5.0.6 on 2024-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0096_remove_rangedweapon_base"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rangedweapon",
            old_name="base_new",
            new_name="base",
        ),
    ]
