# Generated by Django 5.0.6 on 2024-07-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0098_delete_rangedweapontemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillnew",
            name="stat",
            field=models.CharField(
                choices=[
                    ("FIT", "FIT"),
                    ("REF", "REF"),
                    ("LRN", "LRN"),
                    ("INT", "INT"),
                    ("PSY", "PSY"),
                    ("WIL", "WIL"),
                    ("CHA", "CHA"),
                    ("POS", "POS"),
                    ("MOV", "MOV"),
                    ("DEX", "DEX"),
                    ("IMM", "IMM"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="skillnew",
            name="type",
            field=models.CharField(
                choices=[
                    ("Physical", "Physical"),
                    ("Combat", "Combat"),
                    ("Specialty", "Specialty"),
                    ("Education", "Education"),
                    ("Social", "Social"),
                    ("Mystical", "Mystical"),
                    ("Mage", "Mage"),
                    ("Priest", "Priest"),
                    ("Language", "Language"),
                ],
                max_length=64,
            ),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
