# Generated by Django 5.0.6 on 2024-07-17 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0099_alter_skillnew_stat_alter_skillnew_type_delete_skill"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RangedWeaponTemplateNew",
            new_name="RangedWeaponTemplate",
        ),
    ]
