# Generated by Django 5.0.6 on 2024-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0101_rename_weapontemplatenew_weapontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="basefirearm",
            name="required_skills",
            field=models.ManyToManyField(blank=True, to="sheet.skillnew"),
        ),
        migrations.AddField(
            model_name="rangedweapontemplate",
            name="required_skills",
            field=models.ManyToManyField(blank=True, to="sheet.skillnew"),
        ),
        migrations.AddField(
            model_name="weapontemplate",
            name="required_skills",
            field=models.ManyToManyField(blank=True, to="sheet.skillnew"),
        ),
    ]
