# Generated by Django 5.0.6 on 2024-07-18 14:17

from django.db import migrations

def weapon_templates(apps, schema_editor, model_name="WeaponTemplate"):
    Weapon = apps.get_model('sheet', model_name)

    for wt in Weapon.objects.all():
        if wt.skill:
            wt.required_skills.add(wt.skill)
        if wt.skill2:
            wt.required_skills.add(wt.skill2)


def ranged_weapon_templates(apps, schema_editor):
    weapon_templates(apps, schema_editor, model_name="RangedWeaponTemplate")


def basefirearms(apps, schema_editor):
    weapon_templates(apps, schema_editor, model_name="BaseFirearm")


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0102_basefirearm_required_skills_and_more"),
    ]

    operations = [
        migrations.RunPython(basefirearms,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(ranged_weapon_templates,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(weapon_templates,
                             reverse_code=migrations.RunPython.noop),
    ]
