# Generated by Django 5.0.6 on 2024-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0105_rename_skillnew_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapontemplate",
            name="is_natural_weapon",
            field=models.BooleanField(
                default=False,
                help_text="Marks the weapon as natural weapon, which affects damage, lethality and durability calculations",
            ),
        ),
        migrations.AddField(
            model_name="edgelevel",
            name="toughness",
            field=models.IntegerField(
                default=0,
                help_text="Level of toughness, decreasing damage effects and increasing body",
            ),
        ),
    ]
