# Generated by Django 5.0.6 on 2024-07-19 13:52

from django.db import migrations


def edge_levels(apps, schema_editor):
    EdgeLevel = apps.get_model('sheet', "EdgeLevel")

    for el in EdgeLevel.objects.all():
        if el.edge.name == "Toughness":
            el.toughness = el.level
            el.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0106_weapontemplate_is_natural_weapon_edgelevel_toughness"),
    ]

    operations = [
        migrations.RunPython(edge_levels,
                             reverse_code=migrations.RunPython.noop),
    ]
