# Generated by Django 5.0.6 on 2024-07-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0107_toughness_to_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="affected_by_armor_mod_climb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="affected_by_armor_mod_conceal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="affected_by_armor_mod_stealth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="affected_by_armor_mod_swim",
            field=models.BooleanField(default=False),
        ),
    ]
