# Generated by Django 5.0.6 on 2024-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0110_skill_armor_mods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponquality",
            name="damage",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="weaponquality",
            name="leth",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
