# Generated by Django 5.0.6 on 2024-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0112_alter_edgeskillbonus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ammunition",
            name="cartridge_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="Additional weight for cartridge and propellant. A `null` value means cartridge weight is counted as 2.5 times the weight of the bullet.",
                max_digits=7,
                null=True,
            ),
        ),
    ]
