# Generated by Django 5.0.6 on 2024-09-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0113_ammunition_cartridge_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ammunition",
            name="cartridge_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="Explicit weight for cartridge (bullet, casing, propellant). A `null` value means cartridge weight is counted as 2.5 times the weight of the bullet.",
                max_digits=7,
                null=True,
            ),
        ),
    ]
