# Generated by Django 5.0.6 on 2025-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0115_ammunition_ammo_usage_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="armorspecialquality",
            name="mana",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="armorspecialquality",
            name="stamina",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="base_mod_mana",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="base_mod_stamina",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="edgelevel",
            name="mana",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="edgelevel",
            name="stamina",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transienteffect",
            name="mana",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transienteffect",
            name="stamina",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weaponspecialquality",
            name="mana",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weaponspecialquality",
            name="stamina",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="skill",
            name="stat",
            field=models.CharField(
                choices=[
                    ("FIT", "FIT"),
                    ("REF", "REF"),
                    ("LRN", "LRN"),
                    ("INT", "INT"),
                    ("PSY", "PSY"),
                    ("WIL", "WIL"),
                    ("CHA", "CHA"),
                    ("POS", "POS"),
                    ("MOV", "MOV"),
                    ("DEX", "DEX"),
                    ("IMM", "IMM"),
                    ("STAMINA", "STAMINA"),
                    ("MANA", "MANA"),
                ],
                max_length=64,
            ),
        ),
    ]
