# Generated by Django 5.0.6 on 2025-07-03 21:09

from django.db import migrations


def forward_quality(apps, schema_editor):
    ArmorQuality = apps.get_model('sheet', "ArmorQuality")

    for aq in ArmorQuality.objects.all():
        aq.mod_vision = aq.mod_sensory
        aq.mod_hear = aq.mod_sensory
        aq.mod_smell = aq.mod_sensory
        aq.mod_surprise = aq.mod_sensory
        aq.save()


def backward_quality(apps, schema_editor):
    ArmorQuality = apps.get_model('sheet', "ArmorQuality")

    for aq in ArmorQuality.objects.all():
        aq.mod_sensory = aq.mod_smell
        aq.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0118_armorquality_mod_hear_armorquality_mod_smell_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_quality,
                             reverse_code=backward_quality),
    ]
