# Generated by Django 5.0.6 on 2025-07-03 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sheet", "0119_sensory_to_senses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="armorquality",
            name="mod_sensory",
        ),
        migrations.RemoveField(
            model_name="armortemplate",
            name="mod_tumble",
        ),
    ]
