# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_weapon_combat_to_cc_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgelevel',
            name='extra_skill_points',
            field=models.IntegerField(default=0),
        ),
    ]
