# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 19:37
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    EdgeLevel = apps.get_model('sheet', 'EdgeLevel')

    for el in EdgeLevel.objects.all():
        sp = None
        if el.edge.name.startswith("Childhood Education"):
            sp = 8
        elif el.edge.name.startswith("Specialist Training"):
            if el.level == 1:
                sp = 6
            elif el.level == 2:
                sp = 10

        if sp is not None:
            el.extra_skill_points = sp
            el.save()
            print("Updated {} {} to {} skill points".format(el.edge.name,
                                                            el.level, sp))


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_edgelevel_extra_skill_points'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
