# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_skill_points_for_childhood_spectraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
