# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0013_auto_20160209_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMiscellaneousItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.MiscellaneousItem')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.Sheet')),
            ],
        ),
    ]
