# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    def forwards(apps, schema_editor):
        MiscellaneousItem = apps.get_model('sheet', 'MiscellaneousItem')
        SheetMiscellaneousItem = apps.get_model('sheet',
                                               'SheetMiscellaneousItem')

        for mi in MiscellaneousItem.objects.all():
            for sheet in mi.sheet_set.all():
                SheetMiscellaneousItem.objects.create(sheet=sheet, item=mi)

    def backwards(apps, schema_editor):
        SheetMiscellaneousItem = apps.get_model('sheet',
                                                'SheetMiscellaneousItem')
        Sheet = apps.get_model('sheet', 'Sheet')

        for mi in SheetMiscellaneousItem.objects.all():
            sheet = Sheet.objects.get(pk=mi.sheet)
            sheet.miscellaneous_items.add(mi.item)
            mi.delete()

    dependencies = [
        ('sheet', '0014_sheetmiscellaneousitem'),
    ]

    operations = [
    ]
