# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0016_remove_sheet_miscellaneous_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='miscellaneous_items',
            field=models.ManyToManyField(blank=True, through='sheet.SheetMiscellaneousItem', to='sheet.MiscellaneousItem'),
        ),
    ]
