# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0017_sheet_miscellaneous_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='edges_bought',
        ),
    ]
