# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0020_auto_20161120_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stamina_damage',
            field=models.IntegerField(default=0),
        ),
    ]
