# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0021_character_stamina_damage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[(b'H', b'Head'), (b'T', b'Torso'), (b'RA', b'Right arm'), (b'LA', b'Left arm'), (b'RL', b'Right leg'), (b'LL', b'Left leg')], max_length=2)),
                ('damage', models.PositiveIntegerField(default=0, help_text=b'Initial damage from the wound.')),
                ('healed', models.PositiveIntegerField(default=0, help_text=b'Healed damage.  When this becomes equal to damage, the wound is healed.')),
                ('effect', models.CharField(blank=True, help_text=b'Initial effect from the injury.', max_length=64)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds', to='sheet.Character')),
            ],
        ),
    ]
