# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0029_firearmaddon_perks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firearmaddon',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['name']},
        ),
    ]
