# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0030_auto_20190809_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='firearmaddon_ptr',
        ),
        migrations.RemoveField(
            model_name='firearm',
            name='scope',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
