# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0031_auto_20190809_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('target_i_mod', models.IntegerField(default=0)),
                ('to_hit_mod', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=256)),
                ('sight', models.IntegerField(default=1000, help_text="Overrides weapon's sight modifier")),
                ('perks', models.ManyToManyField(blank=True, to='sheet.EdgeLevel')),
                ('tech_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.TechLevel')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='firearm',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firearms_using_scope', to='sheet.Scope'),
        ),
    ]
