# Generated by Django 2.0.13 on 2019-08-12 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0032_auto_20190809_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefirearm',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_basefirearm', to='sheet.Skill'),
        ),
        migrations.AlterField(
            model_name='basefirearm',
            name='skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for_basefirearm', to='sheet.Skill'),
        ),
        migrations.AlterField(
            model_name='characterlogentry',
            name='edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheet.EdgeLevel'),
        ),
        migrations.AlterField(
            model_name='characterlogentry',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheet.Skill'),
        ),
        migrations.AlterField(
            model_name='firearm',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firearms_using_scope', to='sheet.Scope'),
        ),
        migrations.AlterField(
            model_name='rangedweapon',
            name='ammo_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangedweaponammo_set', to='sheet.WeaponQuality'),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_rangedweapontemplate', to='sheet.Skill'),
        ),
        migrations.AlterField(
            model_name='rangedweapontemplate',
            name='skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for_rangedweapontemplate', to='sheet.Skill'),
        ),
        migrations.AlterField(
            model_name='weapontemplate',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_weapontemplate', to='sheet.Skill'),
        ),
        migrations.AlterField(
            model_name='weapontemplate',
            name='skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for_weapontemplate', to='sheet.Skill'),
        ),
    ]
