# Generated by Django 2.2 on 2023-01-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0033_auto_20190812_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteredge',
            name='ignore_cost',
            field=models.BooleanField(default=False, help_text='Whether edge cost counts against'),
        ),
    ]
